name: CI on compilers

on:
  - push
  - pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    needs: [check-protected-files]

    strategy:
      matrix:
        java: [21, 25]

    steps:
    - name: Checking of the code
      uses: actions/checkout@v4

    - name: Set up JDK 21+
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
        cache: maven

    - name: Build and run tests
      run:
        mvn clean test

  check-protected-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for forbidden file changes
        run: |
          if [[ "$GITHUB_ACTOR" != "myambohlulani" ]]; then
              exit 1
            fi
          PROTECTED_FILES=(
          "pom.xml"
          ".github/workflows/main.yaml"
          "LICENSE"
          )
          CHANGED_FILES=$(git diff --name-only origin/main..HEAD)
          echo "Changed files:"
          echo "${CHANGED_FILES}"
          for file in "${PROTECTED_FILES[@]}"; do
            if echo "${CHANGED_FILES}" | grep -qx "${file}"; then
              echo "Error: ${file} must not me modified."
              exit 1
            fi
          done
          echo "No protected files were modified!"